name: udacity-project-3
on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.UDACIT_PROJECT_3}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./docker-compose-build.yaml
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${ secrets.DOCKERHUB_USERNAME }}/udacity-project-3

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
