name: udacity-project-3
on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.UDACIT_PROJECT_3}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Udagram Feed
        uses: docker/build-push-action@v2
        id: docker_build_feed
        with:
          context: ./udagram-api-feed
          file: ./Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/udagram-api-feed

      - name: Build and Push Udagram USER
        uses: docker/build-push-action@v2
        id: docker_build_user
        with:
          context: ./udagram-api-user
          file: ./Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/udagram-api-user

      - name: Build and Push Udagram Front end
        uses: docker/build-push-action@v2
        id: docker_build_fronend
        with:
          context: ./udagram-frontend
          file: ./Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/udagram-frontend

      - name: Build and Push Udagram Reverseproxy
        uses: docker/build-push-action@v2
        id: docker_build_reverseproxy
        with:
          context: ./udagram-reverseproxy
          file: ./Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/reverseproxy

      - name: Verify
        run: echo ${{steps.docker_build_reverseproxy.outputs.digest}}
